### ISSUE TITLE
Not able to parse feature having property type 'Date'

### ISSUE THREAD

**Issue by brahmgupta** [Smartrak/GeoJsonSharp#1]
When I am trying to parse feature collection with one of the feature's property type as 'Date' I get this error - Expected one of [Float, Integer, Null, String] but got Date

I've downloaded project and added "JsonToken.Date" in AssertRead params and is working fine. Hoping you can add this or have some valid reasons to ignore.

Thanks

**Comment by danzel** [comment]
Do you have a small test file (or even just a snippet) you could provide for this?
We should start adding some tests, and this would be a good one.

**Comment by brahmgupta** [comment]
@danzel I've created small test project to test changes. Kindly review

**Comment by danzel** [comment]
Cool, that'll do for now at least. Thanks!
